# Generated by Django 5.2.4 on 2025-07-16 10:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100, unique=True)),
                ('cat_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='user_phone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pswd',
            new_name='user_pswd',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='user_status',
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=255)),
                ('m_email', models.EmailField(max_length=254, unique=True)),
                ('m_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('m_city', models.CharField(max_length=100)),
                ('m_onboarding_date', models.DateField(blank=True, null=True)),
                ('m_due_date', models.DateField(blank=True, null=True)),
                ('m_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('m_setup_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('m_amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('m_amount_paid_date', models.DateField(blank=True, null=True)),
                ('m_pending_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('m_pending_amount_due_date', models.DateField(blank=True, null=True)),
                ('m_payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_merchants', to='mr_tracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='mr_tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='mr_tracker.user')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_task_name', models.CharField(max_length=255)),
                ('custom_task_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed')], default='pending', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_tasks', to='mr_tracker.category')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mr_tracker.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_tasks', to='mr_tracker.user')),
                ('task_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchant_tasks', to='mr_tracker.tasktemplate')),
            ],
        ),
    ]
