# Generated by Django 5.2.4 on 2025-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_tracker', '0002_category_rename_email_user_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_confirm_pswd',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
