# Generated by Django 5.2.4 on 2025-07-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_tracker', '0003_user_user_confirm_pswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchanttask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
