# Generated by Django 5.2.4 on 2025-07-16 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_tracker', '0004_merchanttask_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantUserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified', models.BooleanField(default=False)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_tracker.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mr_tracker.user')),
            ],
            options={
                'unique_together': {('merchant', 'user')},
            },
        ),
    ]
