# Generated by Django 5.2.4 on 2025-07-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_tracker', '0005_merchantusernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='assigned_support_users',
            field=models.ManyToManyField(blank=True, related_name='categories', to='mr_tracker.user'),
        ),
    ]
