# Generated by Django 5.2.4 on 2025-07-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mr_tracker', '0008_merchanttaskhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='order',
            field=models.IntegerField(default=0, help_text='Order of the task in the template'),
        ),
    ]
